apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bodapay-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: bodapay.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bodapay-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bodapay-frontend
                port:
                  number: 80
